# Generated by Django 5.2.13 on 2026-05-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abstraction", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abstractionrulemodel",
            options={},
        ),
        migrations.AlterModelOptions(
            name="promptpatternmodel",
            options={},
        ),
        migrations.AlterModelOptions(
            name="promptsafetyviolationmodel",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sketchpromptmodel",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="abstractionrulemodel",
            name="abstr_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="promptpatternmodel",
            name="pattern_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="promptsafetyviolationmodel",
            name="violation_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="sketchpromptmodel",
            name="sketch_created_idx",
        ),
        migrations.RenameIndex(
            model_name="abstractionrulemodel",
            new_name="abstraction_session_f3f8e4_idx",
            old_name="abstr_sess_idx",
        ),
        migrations.RenameIndex(
            model_name="abstractionrulemodel",
            new_name="abstraction_concept_b9c1e9_idx",
            old_name="abstr_conc_idx",
        ),
        migrations.RenameIndex(
            model_name="abstractionrulemodel",
            new_name="abstraction_axis_05dc44_idx",
            old_name="abstr_axis_idx",
        ),
        migrations.RenameIndex(
            model_name="promptpatternmodel",
            new_name="prompt_patt_categor_2148fa_idx",
            old_name="pattern_cat_idx",
        ),
        migrations.RenameIndex(
            model_name="promptpatternmodel",
            new_name="prompt_patt_active_10fdef_idx",
            old_name="pattern_active_idx",
        ),
        migrations.RenameIndex(
            model_name="promptsafetyviolationmodel",
            new_name="prompt_safe_session_643885_idx",
            old_name="violation_sess_idx",
        ),
        migrations.RenameIndex(
            model_name="promptsafetyviolationmodel",
            new_name="prompt_safe_prompt__219378_idx",
            old_name="violation_prompt_idx",
        ),
        migrations.RenameIndex(
            model_name="sketchpromptmodel",
            new_name="sketch_prom_session_f2c025_idx",
            old_name="sketch_sess_idx",
        ),
        migrations.RenameIndex(
            model_name="sketchpromptmodel",
            new_name="sketch_prom_kind_621119_idx",
            old_name="sketch_kind_idx",
        ),
        migrations.AlterField(
            model_name="abstractionrulemodel",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="promptpatternmodel",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="promptsafetyviolationmodel",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sketchpromptmodel",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name="abstractionrulemodel",
            index=models.Index(
                fields=["created_at"], name="abstraction_created_39d903_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptpatternmodel",
            index=models.Index(
                fields=["created_at"], name="prompt_patt_created_5af263_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptsafetyviolationmodel",
            index=models.Index(
                fields=["created_at"], name="prompt_safe_created_66127a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sketchpromptmodel",
            index=models.Index(
                fields=["created_at"], name="sketch_prom_created_e09876_idx"
            ),
        ),
    ]
