# Generated by Django 5.2.13 on 2026-05-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DesignProject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("industrial", "Industrial Design"),
                            ("fashion", "Fashion Design"),
                            ("visual", "Visual Design"),
                            ("advertising", "Advertising Design"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("owner_id", models.UUIDField(db_index=True)),
            ],
            options={
                "verbose_name": "Design Project",
                "verbose_name_plural": "Design Projects",
                "db_table": "design_projects",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "status"],
                        name="design_proj_workspa_e5a7f2_idx",
                    ),
                    models.Index(
                        fields=["owner_id"], name="design_proj_owner_i_730121_idx"
                    ),
                    models.Index(
                        fields=["domain"], name="design_proj_domain_b2e950_idx"
                    ),
                ],
            },
        ),
    ]
