# Generated by Django 5.2.13 on 2026-05-08 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelProviderModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("api_key_env", models.CharField(max_length=255)),
                ("base_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "endpoint_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "auth_scheme",
                    models.CharField(
                        choices=[
                            ("Bearer", "BEARER"),
                            ("ApiKey", "API_KEY"),
                            ("Basic", "BASIC"),
                            ("Custom", "CUSTOM"),
                        ],
                        default="Bearer",
                        max_length=50,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Model Provider",
                "verbose_name_plural": "Model Providers",
                "db_table": "model_providers",
                "indexes": [
                    models.Index(
                        fields=["name", "active"], name="model_provi_name_b7c58c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelCatalogModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("model_name", models.CharField(db_index=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "TEXT"),
                            ("chat", "CHAT"),
                            ("vision", "VISION"),
                            ("image", "IMAGE"),
                            ("search", "SEARCH"),
                            ("embedding", "EMBEDDING"),
                            ("multimodal", "MULTIMODAL"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("context_limit", models.IntegerField(blank=True, null=True)),
                (
                    "cost_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("modalities", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="models",
                        to="model_catalog.modelprovidermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Catalog Entry",
                "verbose_name_plural": "Model Catalog Entries",
                "db_table": "model_catalog",
            },
        ),
        migrations.CreateModel(
            name="PolicyChangeLogModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("target_type", models.CharField(db_index=True, max_length=255)),
                ("target_id", models.CharField(db_index=True, max_length=255)),
                ("version_from", models.IntegerField(blank=True, null=True)),
                ("version_to", models.IntegerField()),
                ("actor_id", models.CharField(max_length=255)),
                ("reason", models.TextField()),
            ],
            options={
                "verbose_name": "Policy Change Log",
                "verbose_name_plural": "Policy Change Logs",
                "db_table": "policy_change_logs",
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id", "-created_at"],
                        name="policy_chan_target__6fea6e_idx",
                    ),
                    models.Index(
                        fields=["actor_id", "-created_at"],
                        name="policy_chan_actor_i_f1584c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PromptPolicyModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("feature_key", models.CharField(db_index=True, max_length=255)),
                ("prompt_version", models.CharField(max_length=255)),
                ("system_prompt", models.TextField()),
                ("user_template", models.TextField()),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("reviewer", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Prompt Policy",
                "verbose_name_plural": "Prompt Policies",
                "db_table": "prompt_policies",
                "indexes": [
                    models.Index(
                        fields=["feature_key", "active"],
                        name="prompt_poli_feature_291bbf_idx",
                    )
                ],
                "unique_together": {("feature_key", "prompt_version")},
            },
        ),
        migrations.CreateModel(
            name="FeatureModelPolicyModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "feature_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "max_cost_per_call",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("reviewer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "fallback_models",
                    models.ManyToManyField(
                        blank=True,
                        related_name="fallback_policies",
                        to="model_catalog.modelcatalogmodel",
                    ),
                ),
                (
                    "primary_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_policies",
                        to="model_catalog.modelcatalogmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Model Policy",
                "verbose_name_plural": "Feature Model Policies",
                "db_table": "feature_model_policies",
                "indexes": [
                    models.Index(
                        fields=["feature_key", "active"],
                        name="feature_mod_feature_a8374e_idx",
                    ),
                    models.Index(
                        fields=["version"], name="feature_mod_version_61f45b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelInvocationModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("feature_key", models.CharField(db_index=True, max_length=255)),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("session_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("success", "SUCCESS"),
                            ("failure", "FAILURE"),
                            ("timeout", "TIMEOUT"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("tokens_in", models.IntegerField(blank=True, null=True)),
                ("tokens_out", models.IntegerField(blank=True, null=True)),
                (
                    "cost_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=255, null=True)),
                ("error_summary", models.TextField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invocations",
                        to="model_catalog.modelcatalogmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Invocation",
                "verbose_name_plural": "Model Invocations",
                "db_table": "model_invocations",
                "indexes": [
                    models.Index(
                        fields=["feature_key", "-created_at"],
                        name="model_invoc_feature_e11d9a_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="model_invoc_tenant__76b0cb_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="model_invoc_status_4539b4_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="modelcatalogmodel",
            index=models.Index(
                fields=["provider", "active"], name="model_catal_provide_798b31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelcatalogmodel",
            index=models.Index(
                fields=["type", "active"], name="model_catal_type_c171f0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modelcatalogmodel",
            unique_together={("provider", "model_name")},
        ),
    ]
