# Generated by Django 5.2.13 on 2026-05-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DomainPackModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("domain", models.CharField(max_length=100, unique=True)),
                ("brief_schema", models.JSONField(default=dict)),
                ("evaluation_axes", models.JSONField(default=list)),
                ("generation_outputs", models.JSONField(default=list)),
                ("spec_template_uri", models.CharField(max_length=500)),
                ("spec_sections", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Domain Pack",
                "verbose_name_plural": "Domain Packs",
                "db_table": "domain_packs",
            },
        ),
        migrations.CreateModel(
            name="SpecDocumentModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("session_id", models.UUIDField(db_index=True)),
                ("domain", models.CharField(db_index=True, max_length=50)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("sections", models.JSONField(default=list)),
                ("evidence_links", models.JSONField(default=list)),
                ("created_by", models.UUIDField(db_index=True)),
                ("approved_by", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "supersedes_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("version_diff", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Spec Document",
                "verbose_name_plural": "Spec Documents",
                "db_table": "spec_documents",
                "ordering": ["-version"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "-version"],
                        name="spec_docume_session_c9d9b9_idx",
                    ),
                    models.Index(
                        fields=["status"], name="spec_docume_status_76e870_idx"
                    ),
                    models.Index(
                        fields=["domain"], name="spec_docume_domain_f025ad_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="spec_docume_created_292547_idx"
                    ),
                    models.Index(
                        fields=["supersedes_id"], name="spec_docume_superse_38a25a_idx"
                    ),
                ],
            },
        ),
    ]
