# Generated by Django 5.2.13 on 2026-05-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SketchAnalysis",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("sketch_id", models.UUIDField(db_index=True, unique=True)),
                ("intent", models.TextField()),
                ("form_notes", models.TextField()),
                ("structure_notes", models.TextField()),
                ("unclear_points", models.TextField(blank=True)),
                ("keep_elements", models.TextField(blank=True)),
                ("vary_elements", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("hypothesis", "Hypothesis"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="hypothesis",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sketch Analysis",
                "verbose_name_plural": "Sketch Analyses",
                "db_table": "sketch_analyses",
                "indexes": [
                    models.Index(
                        fields=["sketch_id", "status"],
                        name="sketch_anal_sketch__8e8fbd_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSketchAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("session_id", models.UUIDField(db_index=True)),
                ("uploader_id", models.UUIDField()),
                ("original_uri", models.TextField()),
                ("sha256", models.CharField(max_length=64)),
                ("mime_type", models.CharField(max_length=100)),
                ("size_bytes", models.BigIntegerField()),
                ("version", models.IntegerField(default=1)),
                (
                    "parent_asset_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "verbose_name": "User Sketch Asset",
                "verbose_name_plural": "User Sketch Assets",
                "db_table": "user_sketch_assets",
                "indexes": [
                    models.Index(
                        fields=["session_id", "created_at"],
                        name="user_sketch_session_358a51_idx",
                    ),
                    models.Index(
                        fields=["uploader_id"], name="user_sketch_uploade_a7bc3a_idx"
                    ),
                    models.Index(
                        fields=["parent_asset_id", "version"],
                        name="user_sketch_parent__b7dccd_idx",
                    ),
                ],
                "unique_together": {("session_id", "sha256", "version")},
            },
        ),
    ]
