"""Seed data for PromptPattern entries.

REQ-03-PROMPT-001: Prompt pattern library with safety validation.
"""
from apps.abstraction.domain.entities import PromptPattern
from apps.abstraction.domain.value_objects import PromptCategory

# Seed data for prompt patterns
PROMPT_PATTERN_SEEDS = [
    PromptPattern(
        name="Line Art to Rendered Image",
        category=PromptCategory.LINE_TO_RENDER,
        source_reference="Internal: Pattern library v1.0 - Line to render conversion",
        input_slots=["line_art_description", "render_style", "lighting"],
        output_constraints=["Photorealistic output", "Consistent with line art structure"],
        safety_rules=["No copyrighted characters", "No trademarked logos"],
        domain_tags=["industrial", "fashion", "visual"],
        active=True,
    ),
    PromptPattern(
        name="Multi-Reference Fusion",
        category=PromptCategory.MULTI_REFERENCE_FUSION,
        source_reference="Internal: Pattern library v1.0 - Multi-reference synthesis",
        input_slots=["reference_1", "reference_2", "fusion_ratio"],
        output_constraints=["Balanced elements from all references", "Cohesive composition"],
        safety_rules=["Respect copyright of each reference", "No direct copying"],
        domain_tags=["fashion", "visual", "advertising"],
        active=True,
    ),
    PromptPattern(
        name="Product Packaging Design",
        category=PromptCategory.PRODUCT_PACKAGING,
        source_reference="Internal: Pattern library v1.0 - Packaging design templates",
        input_slots=["product_type", "brand_guidelines", "packaging_format"],
        output_constraints=["Brand compliance", "Functional packaging", "Print-ready specs"],
        safety_rules=["No misleading claims", "Regulatory compliance labels"],
        domain_tags=["industrial", "fashion"],
        active=True,
    ),
    PromptPattern(
        name="Material and Texture Rendering",
        category=PromptCategory.MATERIAL_TEXTURE,
        source_reference="Internal: Pattern library v1.0 - Material texture library",
        input_slots=["material_type", "surface_finish", "lighting_condition"],
        output_constraints=["Accurate material representation", "Realistic surface properties"],
        safety_rules=["No proprietary material patterns", "Generic material representations"],
        domain_tags=["industrial", "fashion"],
        active=True,
    ),
    PromptPattern(
        name="Exploded View Generation",
        category=PromptCategory.EXPLODED_VIEW,
        source_reference="Internal: Pattern library v1.0 - Technical illustration standards",
        input_slots=["product_assembly", "explode_distance", "annotation_level"],
        output_constraints=["Clear component separation", "Accurate assembly relationships"],
        safety_rules=["No trade secret exposure", "Generic component representation"],
        domain_tags=["industrial"],
        active=True,
    ),
    PromptPattern(
        name="Storyboard Sequence",
        category=PromptCategory.STORYBOARD,
        source_reference="Internal: Pattern library v1.0 - Narrative visualization",
        input_slots=["narcative_arc", "scene_count", "visual_style"],
        output_constraints=["Consistent visual style", "Clear narrative flow"],
        safety_rules=["No copyrighted storylines", "Original narratives only"],
        domain_tags=["advertising", "visual"],
        active=True,
    ),
    PromptPattern(
        name="Moodboard Collage",
        category=PromptCategory.MOODBOARD_COLLAGE,
        source_reference="Internal: Pattern library v1.0 - Mood design templates",
        input_slots=["theme_keywords", "color_palette", "image_count"],
        output_constraints=["Cohesive aesthetic", "Balanced composition"],
        safety_rules=["No copyrighted images", "Proper image attribution"],
        domain_tags=["fashion", "visual", "advertising"],
        active=True,
    ),
    PromptPattern(
        name="Diagram Annotation",
        category=PromptCategory.DIAGRAM_ANNOTATION,
        source_reference="Internal: Pattern library v1.0 - Technical documentation standards",
        input_slots=["diagram_type", "annotation_density", "label_style"],
        output_constraints=["Clear labels", "Legible at intended size"],
        safety_rules=["No confidential specifications", "Generic examples"],
        domain_tags=["industrial"],
        active=True,
    ),
    PromptPattern(
        name="Domain-Specific Application",
        category=PromptCategory.DOMAIN_APPLICATION,
        source_reference="Internal: Pattern library v1.0 - Domain adaptation patterns",
        input_slots=["domain", "base_concept", "domain_constraints"],
        output_constraints=["Domain compliance", "Industry best practices"],
        safety_rules=["Respect domain regulations", "No domain-specific IP violations"],
        domain_tags=["industrial", "fashion", "visual", "advertising"],
        active=True,
    ),
    PromptPattern(
        name="Refinement with Original Preservation",
        category=PromptCategory.REFINEMENT_PRESERVE_ORIGINAL,
        source_reference="Internal: Pattern library v1.0 - Iterative refinement",
        input_slots=["original_design", "refinement_instruction", "change_extent"],
        output_constraints=["Preserve core identity", "Controlled modifications"],
        safety_rules=["No style mimicry", "Respect original design intent"],
        domain_tags=["industrial", "fashion", "visual", "advertising"],
        active=True,
    ),
]
