# Generated by Django 5.2.13 on 2026-05-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs_tenant__0b1a88_idx",
            old_name="audit_logs_tenant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs_actor_i_850acc_idx",
            old_name="audit_logs_actor_action_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs_workspa_bba528_idx",
            old_name="audit_logs_workspace_created_idx",
        ),
    ]
