# Generated by Django 5.2.13 on 2026-05-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
            },
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_messag_convers_0a903c_idx",
            old_name="chat_messages_conv_created_idx",
        ),
    ]
