# Generated by Django 5.2.13 on 2026-05-08 04:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminMetricsORM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
                (
                    "feature_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
                ),
                ("cost_by_feature", models.JSONField(default=dict)),
                ("total_tokens", models.BigIntegerField(default=0)),
                ("tokens_by_feature", models.JSONField(default=dict)),
                ("prompt_tokens", models.BigIntegerField(default=0)),
                ("completion_tokens", models.BigIntegerField(default=0)),
                ("total_invocations", models.IntegerField(default=0)),
                ("invocations_by_feature", models.JSONField(default=dict)),
                ("successful_invocations", models.IntegerField(default=0)),
                ("failed_invocations", models.IntegerField(default=0)),
                ("failure_rate", models.FloatField(default=0.0)),
                ("failure_reasons", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "admin_metrics",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["period", "-start_date"],
                        name="admin_metri_period_ca067b_idx",
                    ),
                    models.Index(
                        fields=["feature_key", "period", "-start_date"],
                        name="admin_metri_feature_6b83b1_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="admin_metri_created_28ac9f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminSessionORM",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("tenant_admin", "Tenant Admin"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "admin_sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "is_active"],
                        name="admin_sessi_user_id_e137fa_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "is_active"],
                        name="admin_sessi_tenant__944592_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeaturePolicyORM",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feature_key",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("version", models.IntegerField(db_index=True, default=1)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("model_type", models.CharField(max_length=50)),
                ("primary_model", models.CharField(max_length=255)),
                ("fallback_models", models.JSONField(default=list)),
                ("max_retries", models.IntegerField(default=3)),
                ("timeout_seconds", models.IntegerField(default=30)),
                (
                    "max_cost_per_request",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "max_cost_per_day",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "max_cost_per_month",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("required_model_types", models.JSONField(default=list)),
                ("min_context_length", models.IntegerField(default=4096)),
                ("supports_streaming", models.BooleanField(default=False)),
                ("supports_function_calling", models.BooleanField(default=False)),
                ("max_tokens_per_request", models.IntegerField(default=4096)),
                ("created_by", models.UUIDField(db_index=True)),
                ("modified_by", models.UUIDField(db_index=True)),
                ("change_reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "feature_policies",
                "ordering": ["feature_key", "-version"],
                "indexes": [
                    models.Index(
                        fields=["feature_key", "-version"],
                        name="feature_pol_feature_65f0e4_idx",
                    ),
                    models.Index(
                        fields=["is_active", "feature_key"],
                        name="feature_pol_is_acti_11bc28_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyChangeLogORM",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("policy_id", models.CharField(db_index=True, max_length=255)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("feature", "Feature Policy"),
                            ("prompt", "Prompt Policy"),
                        ],
                        default="feature",
                        max_length=20,
                    ),
                ),
                ("version", models.IntegerField(db_index=True)),
                ("changed_by", models.UUIDField(db_index=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("rollback", "Rollback"),
                            ("deactivate", "Deactivate"),
                        ],
                        default="create",
                        max_length=20,
                    ),
                ),
                ("previous_version", models.IntegerField(blank=True, null=True)),
                ("change_summary", models.TextField()),
                ("change_details", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "policy_change_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["policy_id", "-version"],
                        name="policy_chan_policy__9bd053_idx",
                    ),
                    models.Index(
                        fields=["policy_type", "-created_at"],
                        name="policy_chan_policy__c4a2ef_idx",
                    ),
                    models.Index(
                        fields=["changed_by", "-created_at"],
                        name="policy_chan_changed_00039a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PromptPolicyORM",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feature_key",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("version", models.IntegerField(db_index=True, default=1)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("system_prompt", models.TextField()),
                ("user_template", models.TextField()),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=2048)),
                ("top_p", models.FloatField(default=0.9)),
                ("frequency_penalty", models.FloatField(default=0.0)),
                ("presence_penalty", models.FloatField(default=0.0)),
                ("created_by", models.UUIDField(db_index=True)),
                ("modified_by", models.UUIDField(db_index=True)),
                ("change_reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "admin_prompt_policies",
                "ordering": ["feature_key", "-version"],
                "indexes": [
                    models.Index(
                        fields=["feature_key", "-version"],
                        name="admin_promp_feature_f0b9c0_idx",
                    ),
                    models.Index(
                        fields=["is_active", "feature_key"],
                        name="admin_promp_is_acti_98f53c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantORM",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=50,
                    ),
                ),
                ("max_users", models.IntegerField(default=5)),
                ("max_projects", models.IntegerField(default=10)),
                ("max_storage_gb", models.IntegerField(default=10)),
                ("created_by", models.UUIDField()),
                ("settings", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "admin_tenants",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "plan"],
                        name="admin_tenan_is_acti_c39893_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="admin_tenan_created_a1a4c7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTenantRoleORM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_tenant_roles",
                "ordering": ["tenant_id", "role"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "role"],
                        name="user_tenant_tenant__abe22d_idx",
                    ),
                    models.Index(
                        fields=["user_id", "is_active"],
                        name="user_tenant_user_id_a71f4a_idx",
                    ),
                ],
                "unique_together": {("user_id", "tenant_id")},
            },
        ),
    ]
