# Generated by Django 5.2.13 on 2026-05-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageProviderQuota",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("daily_limit", models.IntegerField()),
                ("used_today", models.IntegerField(default=0)),
                ("reset_at", models.DateTimeField(db_index=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Image Provider Quota",
                "verbose_name_plural": "Image Provider Quotas",
                "db_table": "references_image_provider_quota",
                "indexes": [
                    models.Index(
                        fields=["provider", "active"],
                        name="references__provide_cd2bc9_idx",
                    ),
                    models.Index(
                        fields=["reset_at"], name="references__reset_a_4cdd8a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReferenceAnalysis",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("asset_id", models.UUIDField(db_index=True, unique=True)),
                ("relevance", models.FloatField()),
                ("form_grammar", models.TextField(blank=True, null=True)),
                ("structure_grammar", models.TextField(blank=True, null=True)),
                ("material_note", models.TextField(blank=True, null=True)),
                ("symbol_note", models.TextField(blank=True, null=True)),
                ("copy_risk", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Reference Analysis",
                "verbose_name_plural": "Reference Analyses",
                "db_table": "references_analysis",
                "indexes": [
                    models.Index(
                        fields=["asset_id"], name="references__asset_i_3b7720_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReferenceAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("session_id", models.UUIDField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("internal", "Internal"),
                            ("web_page", "Web Page"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=100)),
                ("tier", models.IntegerField()),
                ("thumbnail_uri", models.CharField(max_length=2048)),
                ("thumbnail_max_edge_px", models.IntegerField(default=1024)),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("source_url", models.URLField(blank=True, max_length=2048, null=True)),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=2048, null=True),
                ),
                ("collected_at", models.DateTimeField(db_index=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("license_id", models.CharField(max_length=100)),
                (
                    "license_risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("attribution_text", models.TextField()),
                ("domain_tags", models.JSONField(default=list)),
                ("relevance_reason", models.TextField(blank=True, null=True)),
                ("abstractable_elements", models.JSONField(default=list)),
                ("copy_risk", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Reference Asset",
                "verbose_name_plural": "Reference Assets",
                "db_table": "references_asset",
                "indexes": [
                    models.Index(
                        fields=["session_id", "kind"],
                        name="references__session_2b3bf7_idx",
                    ),
                    models.Index(
                        fields=["provider", "tier"],
                        name="references__provide_952ed7_idx",
                    ),
                    models.Index(
                        fields=["license_risk"], name="references__license_c696c7_idx"
                    ),
                    models.Index(
                        fields=["-collected_at"], name="references__collect_b1ea58_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReferenceQuery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("session_id", models.UUIDField(db_index=True)),
                ("requested_by", models.UUIDField(db_index=True)),
                (
                    "query_kind",
                    models.CharField(
                        choices=[
                            ("keyword", "Keyword"),
                            ("image", "Image"),
                            ("sketch", "Sketch"),
                            ("document", "Document"),
                            ("internal", "Internal"),
                            ("expanded", "Expanded"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("payload", models.TextField()),
            ],
            options={
                "verbose_name": "Reference Query",
                "verbose_name_plural": "Reference Queries",
                "db_table": "references_query",
                "indexes": [
                    models.Index(
                        fields=["session_id", "query_kind"],
                        name="references__session_2df1ec_idx",
                    ),
                    models.Index(
                        fields=["requested_by"], name="references__request_ab876a_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="references__created_0cbf61_idx"
                    ),
                ],
            },
        ),
    ]
