# Generated by Django 5.2.13 on 2026-05-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParsingFailureQueue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("document_id", models.UUIDField(db_index=True, unique=True)),
                ("reason", models.TextField()),
                ("retried_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Parsing Failure",
                "verbose_name_plural": "Parsing Failures",
                "db_table": "trend_knowledge_parsing_failure_queue",
                "indexes": [
                    models.Index(
                        fields=["document_id"], name="trend_knowl_documen_5e350d_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="trend_knowl_created_cb0189_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrendDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("source_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=2048)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("collected_at", models.DateTimeField(db_index=True)),
                ("raw_uri", models.CharField(max_length=2048)),
                (
                    "parsed_text_uri",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("hash", models.CharField(db_index=True, max_length=64)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsing", "Parsing"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trend Document",
                "verbose_name_plural": "Trend Documents",
                "db_table": "trend_knowledge_document",
                "indexes": [
                    models.Index(
                        fields=["source_id", "collected_at"],
                        name="trend_knowl_source__cbd235_idx",
                    ),
                    models.Index(
                        fields=["parse_status"], name="trend_knowl_parse_s_7c3c1d_idx"
                    ),
                    models.Index(fields=["hash"], name="trend_knowl_hash_0878d3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrendInsight",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("document_id", models.UUIDField(db_index=True)),
                ("summary", models.TextField()),
                ("keywords", models.JSONField(default=list)),
                ("domain_tags", models.JSONField(default=list)),
                ("evidence_quote", models.TextField()),
                ("confidence", models.FloatField()),
                ("recency_score", models.FloatField()),
            ],
            options={
                "verbose_name": "Trend Insight",
                "verbose_name_plural": "Trend Insights",
                "db_table": "trend_knowledge_insight",
                "indexes": [
                    models.Index(
                        fields=["document_id"], name="trend_knowl_documen_cf7d75_idx"
                    ),
                    models.Index(
                        fields=["domain_tags"], name="trend_knowl_domain__91660c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrendSource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("url", models.URLField(max_length=2048)),
                ("domain", models.CharField(db_index=True, max_length=100)),
                ("crawl_schedule", models.CharField(max_length=100)),
                ("trust_level", models.CharField(max_length=20)),
                ("license", models.CharField(max_length=100)),
                ("active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Trend Source",
                "verbose_name_plural": "Trend Sources",
                "db_table": "trend_knowledge_source",
                "indexes": [
                    models.Index(
                        fields=["domain", "active"],
                        name="trend_knowl_domain_7fcb76_idx",
                    ),
                    models.Index(
                        fields=["active"], name="trend_knowl_active_a7a68a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrendTaxonomy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("domain", models.CharField(db_index=True, max_length=100)),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("parent_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Trend Taxonomy",
                "verbose_name_plural": "Trend Taxonomies",
                "db_table": "trend_knowledge_taxonomy",
                "indexes": [
                    models.Index(
                        fields=["domain", "active"],
                        name="trend_knowl_domain_0deb78_idx",
                    ),
                    models.Index(
                        fields=["category"], name="trend_knowl_categor_ffe2dc_idx"
                    ),
                    models.Index(
                        fields=["parent_id"], name="trend_knowl_parent__bba1fa_idx"
                    ),
                ],
            },
        ),
    ]
