# Generated by Django 5.2.13 on 2026-05-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="generateddesignmodel",
            new_name="generated_d_job_id_0c3503_idx",
            old_name="gen_des_job_idx",
        ),
        migrations.RenameIndex(
            model_name="generateddesignmodel",
            new_name="generated_d_created_47b41e_idx",
            old_name="gen_des_created_idx",
        ),
        migrations.RenameIndex(
            model_name="generationjobmodel",
            new_name="generation__session_10728c_idx",
            old_name="gen_job_sess_idx",
        ),
        migrations.RenameIndex(
            model_name="generationjobmodel",
            new_name="generation__status_e944f3_idx",
            old_name="gen_job_status_idx",
        ),
        migrations.RenameIndex(
            model_name="generationjobmodel",
            new_name="generation__kind_f85af3_idx",
            old_name="gen_job_kind_idx",
        ),
        migrations.AlterField(
            model_name="generateddesignmodel",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="generationjobmodel",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
