# Generated by Django 5.2.13 on 2026-05-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("design_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="designsession",
            options={
                "verbose_name": "Design Session",
                "verbose_name_plural": "Design Sessions",
            },
        ),
        migrations.RemoveIndex(
            model_name="designsession",
            name="design_sessions_tenant_ws_idx",
        ),
        migrations.RenameIndex(
            model_name="decisionlog",
            new_name="decision_lo_session_d684d1_idx",
            old_name="decision_logs_session_created_idx",
        ),
        migrations.RenameIndex(
            model_name="decisionlog",
            new_name="decision_lo_actor_i_e94efb_idx",
            old_name="decision_logs_actor_created_idx",
        ),
        migrations.RenameIndex(
            model_name="designsession",
            new_name="design_sess_project_a60ca3_idx",
            old_name="design_sessions_proj_status_idx",
        ),
        migrations.RenameIndex(
            model_name="designsession",
            new_name="design_sess_tenant__45d805_idx",
            old_name="design_sessions_tenant_ws_status_idx",
        ),
        migrations.RenameIndex(
            model_name="designsession",
            new_name="design_sess_started_a449a9_idx",
            old_name="design_sessions_started_by_idx",
        ),
    ]
