# Generated by Django 5.2.13 on 2026-05-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0002_add_risks"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conceptcandidatemodel",
            new_name="concept_can_session_d69c58_idx",
            old_name="concept_cand_session_idx",
        ),
        migrations.RenameIndex(
            model_name="conceptcandidatemodel",
            new_name="concept_can_status_32db83_idx",
            old_name="concept_cand_status_idx",
        ),
        migrations.RenameIndex(
            model_name="conceptcandidatemodel",
            new_name="concept_can_created_6672dd_idx",
            old_name="concept_cand_created_idx",
        ),
        migrations.RenameIndex(
            model_name="conceptdecisionmodel",
            new_name="concept_dec_concept_5d07b6_idx",
            old_name="concept_decision_concept_idx",
        ),
        migrations.RenameIndex(
            model_name="conceptdecisionmodel",
            new_name="concept_dec_created_530a9e_idx",
            old_name="concept_decision_created_idx",
        ),
        migrations.AlterField(
            model_name="conceptcandidatemodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="conceptcandidatemodel",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="conceptdecisionmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="conceptdecisionmodel",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
