# Generated by Django 5.2.13 on 2026-05-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.UUIDField(db_index=True)),
                ("workspace_id", models.UUIDField(db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("lead", "Lead"),
                            ("designer", "Designer"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "db_table": "workspaces_membership",
                "indexes": [
                    models.Index(
                        fields=["user_id", "workspace_id"],
                        name="workspaces__user_id_5e5274_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "role"],
                        name="workspaces__workspa_071777_idx",
                    ),
                ],
                "unique_together": {("user_id", "workspace_id")},
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "workspaces_tenant",
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="workspaces__is_acti_cddf55_idx"
                    ),
                    models.Index(fields=["plan"], name="workspaces__plan_c13d7c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Workspace",
                "verbose_name_plural": "Workspaces",
                "db_table": "workspaces_workspace",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "is_active"],
                        name="workspaces__tenant__724b48_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "is_active"],
                        name="workspaces__workspa_46573c_idx",
                    ),
                ],
            },
        ),
    ]
